//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeClientAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int Id { get; set; }
        public int IdUser { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> TypeCrust1 { get; set; }
        public Nullable<int> TypeCrust2 { get; set; }
        public Nullable<int> TypeCrust3 { get; set; }
        public Nullable<int> TypeFilling1 { get; set; }
        public Nullable<int> TypeFilling2 { get; set; }
        public Nullable<int> TypeFilling3 { get; set; }
        public Nullable<int> TypeCream1 { get; set; }
        public Nullable<int> TypeCream2 { get; set; }
        public Nullable<int> TypeCream3 { get; set; }
        public Nullable<int> TypeAddition1 { get; set; }
        public Nullable<int> TypeAddition2 { get; set; }
        public Nullable<int> TypeAddition3 { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Additions Additions { get; set; }
        public virtual Additions Additions1 { get; set; }
        public virtual Additions Additions2 { get; set; }
        public virtual Creams Creams { get; set; }
        public virtual Creams Creams1 { get; set; }
        public virtual Creams Creams2 { get; set; }
        public virtual Crusts Crusts { get; set; }
        public virtual Crusts Crusts1 { get; set; }
        public virtual Crusts Crusts2 { get; set; }
        public virtual Fillings Fillings { get; set; }
        public virtual Fillings Fillings1 { get; set; }
        public virtual Fillings Fillings2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual User User { get; set; }
    }
}
